Create logic module
legafise/Stores pull request #4
Opened 2020-09-03 16:27 UTC by legafise

2020-09-04 22:14 UTC, IvanYarochkin requested changes

2020-09-04 22:14 UTC, IvanYarochkin commented on store-logic/pom.xml
> +    </parent>
Move it below the `artifactId, versopm and packaging`

2020-09-04 22:14 UTC, IvanYarochkin commented on store-logic/pom.xml
> +    <packaging>jar</packaging>
Use pom packaging

2020-09-04 22:14 UTC, IvanYarochkin commented on store-logic/pom.xml
> +
Remove the space

2020-09-05 10:26 UTC, legafise commented on store-logic/pom.xml
> +
Done

2020-09-05 10:26 UTC, legafise commented on store-logic/pom.xml
> +    <packaging>jar</packaging>
Done

2020-09-08 21:40 UTC, IvanYarochkin commented on store-logic/pom.xml
> +    </parent>
Don't forget to type done or something like this XD

2020-09-08 21:40 UTC, IvanYarochkin commented on store-logic/pom.xml
> +    <packaging>jar</packaging>
The next time type something like: "Keep the packaging jas because ..."

2020-09-08 21:41 UTC, IvanYarochkin commented on store-logic/pom.xml
> +    <packaging>jar</packaging>
Or as discussed with Ivan jar packaging is kept

2020-09-08 21:42 UTC, IvanYarochkin approved these changes

2020-09-08 21:42 UTC, merged