Update logic module
legafise/Stores pull request #5
Opened 2020-09-29 21:16 UTC by legafise

2020-10-12 22:30 UTC, IvanYarochkin commented on store-logic/src/main/java/com/lashkevich/stores/util/reader/impl/NNSProdPropertiesReader.java
> +    private static final String CONFIG_PATH = "D:\\Project\\Stores\\store-logic\\src\\main\\resources\\db_config.properties";
Don't use full path and move it to properties

2020-10-12 22:30 UTC, IvanYarochkin commented on store-logic/src/main/java/com/lashkevich/stores/util/validator/NNSGoodValidator.java
> +        return price != null && price.compareTo(new BigDecimal(MIN_PRICE)) > 0;
`price.compareTo(new BigDecimal(MIN_PRICE)) > 0` does that have any sense?

2020-10-12 22:30 UTC, IvanYarochkin requested changes
Resolve listed issues

2020-10-13 16:09 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSGoodService.java
> +        return goods;
Done

2020-10-13 16:13 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSCurrencyService.java
> +                throw new NNSServiceStoreException();
Done

2020-10-13 16:44 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSBasketService.java
> +    private static final String STANDARD_CURRENCY_ID = "1";
Done

2020-10-13 16:47 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSBasketService.java
> +            if (isValidBasket && isDuplicateBasket && isValidGood(basket.getGoods()) && isGoodCreated(basket, goodService.findAllGoods("1")) &&
Done

2020-10-13 16:50 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/dao/impl/NNSCurrencyDao.java
> +            return currencyOptional;
Done

2020-10-13 22:51 UTC, IvanYarochkin requested changes

2020-10-13 22:51 UTC, IvanYarochkin commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSCurrencyService.java
> +    private static final String EMPTY_CURRENCY_ERROR_MESSAGE = "Currency is empty";
`Currency is empty` means `Валюта пустая`

I suggest using `Currency with {id} id doesn't exist` which means `Валюты с таким-то id не существует`

2020-10-13 22:55 UTC, IvanYarochkin requested changes

2020-10-13 22:55 UTC, IvanYarochkin commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSGoodService.java
> +        return goods.stream().map(currentGood -> NNSGoodPriceConverter.convert(currentGood, currency)).collect(Collectors.toList());
Break it to lines:


`return goods.stream()`
`        .map(currentGood -> NNSGoodPriceConverter.convert(currentGood, currency))`
`        .collect(Collectors.toList());`

2020-10-15 15:31 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSGoodService.java
> +        return goods.stream().map(currentGood -> NNSGoodPriceConverter.convert(currentGood, currency)).collect(Collectors.toList());
Done

2020-10-15 15:53 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSCurrencyService.java
> +    private static final String EMPTY_CURRENCY_ERROR_MESSAGE = "Currency is empty";
Done

2020-10-15 15:55 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSBasketService.java
> +        if (currencies.stream().filter(currentCurrency -> currentCurrency.getSymbol().equals("$")).count() != 1) {
Done

2020-10-15 16:52 UTC, IvanYarochkin requested changes

2020-10-15 16:52 UTC, IvanYarochkin commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSCurrencyService.java
> +    private static final String CURRENCY_ID_DOES_NOT_EXIST_ERROR_MESSAGE_SECOND_PART = " doesn't exist";
Use `private static final String CURRENCY_NOT_EXIST_MESSAGE = "Currency with id =  %s doesn't exist";` then you are easily use `String.format(CURRENCY_NOT_EXIST_MESSAGE, id);`

2020-10-15 16:55 UTC, IvanYarochkin requested changes

2020-10-15 16:55 UTC, IvanYarochkin commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSBasketService.java
> +    private static final String STANDARD_CURRENCY_SYMBOL = "$";
Use `USD` instead the sign.

2020-10-15 16:55 UTC, IvanYarochkin commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSBasketService.java
> +            String standardCurrencyId = findStandardCurrencyId(currencyService.findAllCurrencies());
Create method of currency service which will take standart currency id. It will be faster than find all currencies and then filter it.

2020-10-15 21:14 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSCurrencyService.java
> +    private static final String CURRENCY_ID_DOES_NOT_EXIST_ERROR_MESSAGE_SECOND_PART = " doesn't exist";
Done

2020-10-16 21:38 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSBasketService.java
> +    private static final String STANDARD_CURRENCY_SYMBOL = "$";
Done

2020-10-16 21:38 UTC, legafise commented on store-logic/src/main/java/com/lashkevich/stores/service/impl/NNSCurrencyService.java
> +    private static final String CURRENCY_ID_DOES_NOT_EXIST_ERROR_MESSAGE_SECOND_PART = " doesn't exist";
Done

2020-10-17 19:42 UTC, IvanYarochkin approved these changes

2020-10-17 19:43 UTC, merged